{
  "openapi": "3.0.0",
  "info": {
    "title": "chain-abstraction",
    "version": "0.4.0"
  },
  "paths": {
    "/resolveChain": {
      "post": {
        "operationId": "resolveChain",
        "summary": "Resolve chain metadata",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "chain_name": {
                    "type": "string"
                  }
                },
                "required": [
                  "chain_name"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/validateAddress": {
      "post": {
        "operationId": "validateAddress",
        "summary": "Validate address for chain",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "chain_name": {
                    "type": "string"
                  },
                  "address": {
                    "type": "string"
                  }
                },
                "required": [
                  "chain_name",
                  "address"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  }
}
