{
  "openapi": "3.0.0",
  "info": {
    "title": "consensus-validator-ops",
    "version": "0.4.0"
  },
  "paths": {
    "/validatorRotationPlan": {
      "post": {
        "operationId": "validatorRotationPlan",
        "summary": "Return validator rotation template refs",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "chain_name": {
                    "type": "string"
                  }
                },
                "required": [
                  "chain_name"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  }
}
